CoreShoppingAdminPortal/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreShoppingAdminPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreShoppingAdminPortal.Controllers
{
    public class ProductCategoryController : Controller
    {
        ShopDataDbContext context;
        public ProductCategoryController(ShopDataDbContext _context)
        {
            context = _context;
        }
        public ViewResult Index()
        {
            var pc = context.Categories.ToList();
            return View(pc);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ProductCategory productcategory)
        {
            context.Categories.Add(productcategory);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        public ViewResult Details(int id)
        {
            ProductCategory category = context.Categories.
                   Where(x => x.ProductCategoryId == id).SingleOrDefault();
            return View(category);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var pc = context.Categories.Where(x => x.ProductCategoryId == id).SingleOrDefault();
            return View(pc);
        }
        [HttpPost]
        public ActionResult Delete(int id, ProductCategory d1)
        {
            var pc = context.Categories.Where(x => x.ProductCategoryId == id).SingleOrDefault();
            context.Categories.Remove(pc);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
              var pc = context.Categories.Where(x => x.ProductCategoryId == id).SingleOrDefault();
            //ViewBag.Categories =
            //    new SelectList(context.Categories, "CategoryId", "CategoryName", pc.ProductCategoryId);
            return View(pc);
        }
        [HttpPost]
        public ActionResult Edit(ProductCategory productcategory,int id)
        {
            var pc = context.Categories.Where(x => x.ProductCategoryId == id).SingleOrDefault();

            //prod.ProductCategoryId = productcategory.ProductCategoryId;
            //prod.CategoryName = productcategory.CategoryName;
            //prod.CategoryDescription = productcategory.CategoryDescription;
            context.Entry(pc).CurrentValues.SetValues(productcategory);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CoreShoppingAdminPortal/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreShoppingAdminPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreShoppingAdminPortal.Controllers
{
    public class ProductController : Controller
    {
        ShopDataDbContext context;
        public ProductController(ShopDataDbContext _context)
        {
            context = _context;
        }
        public ViewResult Index()
        {
            var pc = context.Products.ToList();
            return View(pc);
        }
        [HttpGet]
        public IActionResult Create()
        {

            ViewBag.products = new SelectList(context.Vendors, "VendorId", "VendorName");
            ViewBag.products1 = new SelectList(context.Categories, "ProductCategoryId", "CategoryName");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Product product)
        {
            context.Products.Add(product);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        public ViewResult Details(int id)
        {
            Product product = context.Products.
                   Where(x => x.ProductId == id).SingleOrDefault();
            return View(product);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var pc = context.Products.Where(x => x.ProductId == id).SingleOrDefault();
            return View(pc);
        }
        [HttpPost]
        public ActionResult Delete(int id, Product d1)
        {
            var pc = context.Products.Where(x => x.ProductId == id).SingleOrDefault();
            context.Products.Remove(pc);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var pc = context.Products.Where(x => x.ProductId == id).SingleOrDefault();
            ViewBag.Categories =
            new SelectList(context.Categories, "ProductCategoryId", "CategoryName",pc.ProductCategoryId);
            ViewBag.Vendor =
            new SelectList(context.Vendors, "VendorId", "VendorName",pc.VendorId);
            return View(pc);
        }
        [HttpPost]
        public ActionResult Edit(Product product, int id)
        {
            var pc = context.Products.Where(x => x.ProductId == product.ProductId).SingleOrDefault();

            //prod.ProductCategoryId = productcategory.ProductCategoryId;
            //prod.CategoryName = productcategory.CategoryName;
            //prod.CategoryDescription = productcategory.CategoryDescription;
            context.Entry(pc).CurrentValues.SetValues(product);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CoreShoppingAdminPortal/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreShoppingAdminPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreShoppingAdminPortal.Controllers
{
    public class VendorController : Controller
    {
        ShopDataDbContext context;
        public VendorController(ShopDataDbContext _context)
        {
            context = _context;
        }
        public IActionResult Index()
        {
            var vendors = context.Vendors.ToList();

            return View(vendors);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var cc = context.Vendors.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult Create(Vendor vendor)
        {
            context.Vendors.Add(vendor);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Vendor auth = context.Vendors.Where(x => x.VendorId == id).SingleOrDefault();
            
            return View(auth);
        }
        [HttpPost]
        public ActionResult Edit(Vendor authr, int id)
        {
            Vendor auth = context.Vendors.Where(x => x.VendorId == id).SingleOrDefault();
            context.Entry(auth).CurrentValues.SetValues(authr);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ViewResult Details(int id)
        {
            Vendor vendor = context.Vendors.
             Where(x => x.VendorId == id).SingleOrDefault();
            return View(vendor);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Vendor auth = context.Vendors.Where(x => x.VendorId == id).
                SingleOrDefault();
            return View(auth);
        }
        [HttpPost]
        public ActionResult Delete(int id, Vendor a1)
        {
            var auth = context.Vendors.Where(x => x.VendorId == id).
                SingleOrDefault();
            context.Vendors.Remove(auth);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

CoreShoppingAdminPortal/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Http;

<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width-device,initial-scale=1.0" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/StarterTemplate.css" />
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="Index">Try & Buy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="ProductCategory" asp-action="Index">Product Category <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Vendor" asp-action="Index">Vendor</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Product" asp-action="Index">Product</a>
                </li>

            </ul>
            <form class="form-inline my-2 my-lg-0">
                <label class="form-control">
                     Welcome @Context.Session.GetString("uname")!!
                </label>
                &nbsp;
                <a asp-action="Logout" asp-controller="Account" class="btn btn-secondary my-sm-0">Logout</a>
            </form>
        </div>
    </nav>
    <main role="main" class="container">
     
            

        <div class="starter-template">
            @RenderBody()
        </div>
        <hr />
    </main>
    <centre>
        <footer class="container">
            <p>&copy; 2019-Try & Buy Shopping Store</p>
        </footer>
    </centre>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

CoreShoppingAdminPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreShoppingAdminPortal</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CoreShoppingAdminPortal</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - CoreShoppingAdminPortal</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>